MODULES = [
    {
        "id": 1,
        "title": "What is SnowWork?",
        "description": "Understand what SnowWork (Falcon) is, how it differs from CoCo, Intelligence, and Raven, and why it matters for AEs.",
        "duration_min": 8,
        "icon": ":material/lightbulb:",
        "lessons": [
            {
                "id": 1,
                "title": "SnowWork in 4 minutes",
                "duration_min": 4,
                "hook": "You're juggling 30+ accounts, your QBR is tomorrow, and your manager just asked for a pipeline update. What if you could get all of that \u2014 briefed, summarized, and ready to go \u2014 in a single conversation?",
                "content": [
                    ("What is Project SnowWork?", "An autonomous enterprise AI platform designed to help business users automate everyday work and turn data into real outcomes. Delivered as a desktop app. Internally, our instance is called **Project Falcon**."),
                    ("Why it matters for AEs", "SnowWork automates the multi-step, cross-system tasks AEs do daily \u2014 account research, meeting prep, pipeline reviews, competitive analysis \u2014 by connecting to Snowhouse, Jira, Confluence, Slack, and other enterprise tools via MCP servers."),
                    ("How it works", "Choose a profile (Sales), get **90+ curated skills** mapped to AE workflows, and interact through natural language or slash commands. Falcon routes to the right skill automatically."),
                    ("Key differentiator", "SnowWork is built on top of governed, trusted Snowflake data with full lineage, RBAC, and masking. It's not an AI that reads files \u2014 it deeply understands your enterprise data model."),
                    ("Accessing SnowWork", "Install the SnowWork desktop app (replaces CoCo Desktop). Sign in with External Browser SSO. Select the **Sales** profile. Your chat history and custom skills from CoCo Desktop migrate automatically."),
                ],
                "pro_tip": "If you've been using CoCo Desktop, SnowWork is its evolution. Your chat history and custom skills migrate automatically when you install the SnowWork app.",
            },
            {
                "id": 2,
                "title": "SnowWork vs. CoCo vs. Intelligence vs. Raven",
                "duration_min": 4,
                "hook": "\"Which AI tool should I use for this?\" is the most common question AEs ask. Here's the definitive answer.",
                "content": [
                    ("SnowWork (Falcon)", "For **business users** who want to automate complex, multi-step tasks without coding. Desktop app with role-specific profiles and 90+ curated skills. Turns intent into finished outputs \u2014 from reprioritizing territories to executive-ready presentations. *Research Preview (external) / Internal Only (Falcon).*"),
                    ("Cortex Code (CoCo)", "For **builders and technical users** \u2014 data engineers, analysts, SEs. AI coding agent in Snowsight or CLI. Best for writing SQL, building pipelines, creating agents. *GA.*"),
                    ("Snowflake Intelligence", "**Enterprise intelligence** for business users asking questions of their data. Web UI. Best for ad-hoc data exploration, visualizations, \"what happened and why.\" *GA with 2,500+ customers.*"),
                    ("Raven", "The **internal Intelligence instance**. Ask questions about your accounts, get prospect research, competitive intel. Best for quick lookups and document search."),
                    ("When to use what", "Need a full account brief with pipeline & consumption? **SnowWork.** Need to write SQL or build a pipeline? **CoCo.** Customer wants to explore their data? **Intelligence.** Quick competitive lookup? **Raven.**"),
                ],
                "pro_tip": "SnowWork and CoCo are complementary. Use SnowWork for your daily selling workflows and CoCo when you need to go deep on technical tasks with your SE.",
            },
        ],
    },
    {
        "id": 2,
        "title": "Account research & daily workflows",
        "description": "Execute core SnowWork skills for account research \u2014 from morning briefings to deep account intelligence and account resolution.",
        "duration_min": 12,
        "icon": ":material/search:",
        "lessons": [
            {
                "id": 3,
                "title": "Your morning briefing",
                "duration_min": 4,
                "hook": "It's 8:00 AM. Before you open Salesforce, open SnowWork. In 60 seconds, you'll know exactly where your week stands.",
                "content": [
                    ("The /account_summarization skill", 'Type "brief me on [company]" or use `/account_summarization [company]`. SnowWork resolves the account, runs **11 parallel data queries** across Raven views, invokes company research and value proposition analysis, and delivers a **10-section brief** including: overview, consumption performance, top performers, pipeline status, contract status, active use cases, recent news, and support tickets.'),
                    ("The /prospect_research skill", "For non-customers, get a 6-7 section prospect brief: company background, industry analysis, value propositions, recommended contacts, and competitive landscape."),
                    ("Your daily workflow", 'Open SnowWork, type **"summarize my top 3 accounts"**, and get a portfolio overview. Look for: consumption changes, expiring contracts, stalled pipeline, and new support tickets.'),
                    ("What you get back", '"Summarize my accounts" returns your full book of business with consumption performance, pipeline status, and contract timelines \u2014 all in one response.'),
                ],
                "pro_tip": "Set a daily habit: SnowWork + coffee. 5 minutes every morning with your account briefs will change how prepared you feel walking into any conversation.",
            },
            {
                "id": 4,
                "title": "Deep account intelligence",
                "duration_min": 4,
                "hook": "Your champion just told you a competitor is in the building. You need intel \u2014 fast.",
                "content": [
                    ("/consumption_insights", "Check **run rate, overage/underage status, and product mix** for any capacity customer. Know whether they're trending up or at risk before the QBR."),
                    ("/tech_stack", "See what **tools and platforms** the account is running (data from Sumble signals). Understand their technology ecosystem to position Snowflake solutions effectively."),
                    ("/contact_intelligence", "Identify **key stakeholders, recent hires, hiring signals, and org changes**. Find new champions or discover that your champion just left."),
                    ("/partner_attachment_intelligence", "Check **partner attach rates, deal registrations, DCP revenue, and co-sell opportunities**. Understand the partner ecosystem around your account."),
                    ("/sec_filing_summary", "For public companies, pull **10-K/10-Q highlights** with earnings call insights and industry trends. Walk into an executive meeting knowing their strategic priorities."),
                ],
                "pro_tip": "Chain skills together in one conversation: \"Give me the account summary for Coinbase, then pull their tech stack and latest 10-K highlights.\" SnowWork handles the routing.",
            },
            {
                "id": 5,
                "title": "The account finder",
                "duration_min": 4,
                "hook": "You heard a company name at a conference. Is it already a Snowflake customer? Who owns it? What segment?",
                "content": [
                    ("/account_finder", "Resolve any company name to its Salesforce account with full metadata: **account_id, type (customer vs. prospect), capacity status, account team (owner, SE, DM, RVP), segment, industry**, and tech stack indicators."),
                    ("When to use it", "Before every first meeting with a new contact. Before requesting an intro from a colleague. Before adding an account to your pipeline."),
                    ("What you get back", "Account ID, type, ownership, segment, industry classification, and a flag for whether it's capacity vs. prospect. No more searching Salesforce manually."),
                    ("Chaining into deeper research", "Once the account is resolved, immediately chain into `/account_summarization` (if capacity) or `/prospect_research` (if prospect) for the full brief."),
                ],
                "pro_tip": "If you're at a conference and meet someone from a company, type \"find account for [company]\" into SnowWork. You'll know if it's your account before the handshake ends.",
            },
        ],
    },
    {
        "id": 3,
        "title": "Meeting prep & customer communications",
        "description": "Prepare for customer meetings in 10 minutes and draft polished follow-ups, executive briefs, and competitive positioning using SnowWork.",
        "duration_min": 10,
        "icon": ":material/edit_note:",
        "lessons": [
            {
                "id": 6,
                "title": "The 10-minute meeting prep",
                "duration_min": 5,
                "hook": "You have a customer call in 15 minutes. You haven't looked at the account in two weeks. Here's how to walk in fully prepared.",
                "content": [
                    ("Step 1: Account brief", '`/account_summarization [company]` \u2014 Full account brief with consumption, pipeline, support tickets, and recent activity.'),
                    ("Step 2: Engagement history", "`/call_email_intelligence` \u2014 Review recent engagement: what was discussed last time, unresolved items, action items that were promised."),
                    ("Step 3: Contact check", "`/contact_intelligence` \u2014 Check who you're meeting with. Any role changes? New hires in the buying group? Champion still in seat?"),
                    ("Step 4: Product positioning", "`/knowledge_discovery_and_self_training` \u2014 Brush up on product positioning or competitive angles relevant to this account's active use cases."),
                    ("The 3-question framework", 'Before every call, ask SnowWork:\n1. "What changed since my last meeting with [account]?"\n2. "What are the open action items?"\n3. "What competitive angles should I be ready for?"'),
                ],
                "pro_tip": "Copy-paste SnowWork's meeting prep summary into your CRM notes before the call. After the call, come back and update with next steps.",
            },
            {
                "id": 7,
                "title": "Customer-facing communications",
                "duration_min": 5,
                "hook": "The follow-up email after a great meeting is where deals accelerate \u2014 or stall. SnowWork writes the first draft in seconds.",
                "content": [
                    ("Post-meeting follow-ups", 'Tell SnowWork: "Draft a follow-up email for my meeting with [company] covering [key topics discussed]." It references your account data, engagement history, and Snowflake\'s value propositions to produce a relevant, personalized email.'),
                    ("Executive briefs", '"Create an executive brief for [company]\'s CISO showing our governance and security capabilities against their current stack." SnowWork pulls from sales knowledge, account data, and competitive positioning.'),
                    ("Competitive positioning", '"Give me the top 3 selling points against [competitor] for [use case]." SnowWork searches internal battlecards, positioning guides, and field-tested talk tracks.'),
                    ("Account plans", '"Generate an account plan for [company]" triggers a comprehensive **8-tab analysis** with use cases, intelligence, AI-powered recommendations, and next steps.'),
                    ("Knowledge search", '`/knowledge_discovery_and_self_training` \u2014 "How does Snowflake position against Databricks on governance?" returns battlecard excerpts with source links.'),
                ],
                "pro_tip": "Always review and personalize SnowWork's drafts before sending. The AI gives you the data-grounded first draft; your relationship knowledge makes it authentic.",
            },
        ],
    },
    {
        "id": 4,
        "title": "Pipeline management & deal strategy",
        "description": "Analyze pipeline health, monitor deal hygiene, and build strategic deal plans using SnowWork's intelligence skills.",
        "duration_min": 8,
        "icon": ":material/analytics:",
        "lessons": [
            {
                "id": 8,
                "title": "Pipeline health & opportunity monitoring",
                "duration_min": 4,
                "hook": "Your DM asks: \"Which deals moved this week?\" Instead of digging through Salesforce, you answer in 10 seconds.",
                "content": [
                    ("/opportunity_monitoring", "Flag deal hygiene issues before your manager does. SnowWork checks: missing close dates, stale stages, deals without next steps, opportunities missing contacts, and pipeline gaps by quarter."),
                    ("Pipeline change tracking", 'Ask "What moved in my pipeline this week?" to get a summary of stage changes, new opportunities, deals closed (won or lost), and push-outs. Perfect for 1:1 prep with your DM.'),
                    ("Consumption-based deal strategy", "For expansion accounts, `/consumption_insights` reveals whether the customer is tracking toward **overage** (expansion trigger) or **underage** (risk signal). Use this to time your expansion conversations."),
                    ("Layering signals", "The most effective AEs layer multiple data points: consumption trending up + contract renewal in 90 days + new use case interest = perfect time for an expansion conversation. SnowWork surfaces all three in one brief."),
                ],
                "pro_tip": "Run /opportunity_monitoring every Monday morning. Fix any hygiene issues before your manager's pipeline review. It takes 2 minutes and saves you 20 minutes of awkward questions.",
            },
            {
                "id": 9,
                "title": "Strategic deal planning",
                "duration_min": 4,
                "hook": "You have a $500K opportunity in Stage 3. How do you multi-thread, position against the incumbent, and get to close faster?",
                "content": [
                    ("Contact mapping", "Use `/contact_intelligence` to identify all stakeholders in the buying group. Look for: economic buyer, technical evaluator, champion, and blocker. SnowWork surfaces org changes and hiring signals that indicate budget shifts."),
                    ("Partner co-sell strategy", "`/partner_attachment_intelligence` shows which partners are already engaged, their DCP contribution, and Crossbeam overlap signals. Use this to activate the right partner at the right deal stage."),
                    ("Competitive intelligence", '"Position Snowflake against [competitor] for [use case] at [account]." The response pulls from battlecards AND account-specific context.'),
                    ("PS attachment", "`/ps_attachment_intelligence` helps you understand when Professional Services should be involved, typical PS attach patterns for similar deals, and project delivery insights from comparable engagements."),
                    ("Account plan generation", '"Generate an account plan for [company]" produces an **8-tab HTML report** combining use case data, company intelligence, and AI-powered strategic recommendations. Use this for your quarterly business reviews.'),
                ],
                "pro_tip": "The best deal strategies use at least 3 SnowWork skills: account intelligence, contact mapping, and competitive positioning. Layer them into a single conversation thread so SnowWork maintains context.",
            },
        ],
    },
    {
        "id": 5,
        "title": "Building your SnowWork power workflow",
        "description": "Create custom skills, design your personal workflow, and master the tool decision framework.",
        "duration_min": 7,
        "icon": ":material/construction:",
        "lessons": [
            {
                "id": 10,
                "title": "Creating custom skills",
                "duration_min": 4,
                "hook": "Every AE has a unique selling rhythm. SnowWork's curated skills cover 90% of your workflow. Custom skills cover the other 10% \u2014 the part that makes you, you.",
                "content": [
                    ("What is a custom skill?", "A reusable workflow you define in natural language that SnowWork saves and executes on demand. Your custom skills are preserved across sessions and app updates."),
                    ("How to create one", 'Just describe what you want: "Create a skill that pulls my pipeline changes from the last 7 days and summarizes what moved, what\'s at risk, and what needs follow-up." SnowWork builds the skill and adds it to your profile.'),
                    ("Example custom skills", '\u2022 **"Monday pipeline digest"** \u2014 weekly pipeline changes, consumption trends, and upcoming renewals\n\u2022 **"Pre-QBR packet"** \u2014 account summary + consumption + pipeline + partner intelligence bundled into one output\n\u2022 **"Competitive alert"** \u2014 surfaces any new competitive mentions or displacement risks across your accounts\n\u2022 **"Deal room prep"** \u2014 for a specific opportunity, pull the account brief, key contacts, competitive positioning, and suggested talk track'),
                    ("Three ways to trigger skills", "1. **Slash command** \u2014 type `/` and select from your skill list\n2. **Natural language** \u2014 describe what you need and Falcon routes automatically\n3. **Skills tab** \u2014 browse the left nav and click \"Use\" on any skill"),
                ],
                "pro_tip": "Build your custom skills iteratively. Start with a simple version, use it for a week, then refine it. The best skills are the ones that match your exact rhythm.",
            },
            {
                "id": 11,
                "title": "Choosing the right tool for every task",
                "duration_min": 3,
                "hook": "You now have SnowWork, CoCo, Snowflake Intelligence, and Raven in your toolkit. Mastery means knowing which one to reach for without thinking.",
                "content": [
                    ("The decision framework", "| Task | Best Tool |\n|---|---|\n| Full account brief with pipeline & consumption | **SnowWork** |\n| Quick product knowledge lookup | **Raven** |\n| Build a demo query or data pipeline with your SE | **CoCo** |\n| Customer wants to explore their own data | **Snowflake Intelligence** |\n| Draft a follow-up email with account context | **SnowWork** |\n| Debug a customer's agent or semantic model | **CoCo** |\n| Competitive battlecard quick reference | **Raven** |\n| Generate account plan with strategic recs | **SnowWork** |\n| Morning prep across your full book of business | **SnowWork** |"),
                    ("The handoff pattern", "Start in **SnowWork** for business context, hand off to **CoCo** when the task turns technical, and use **Raven** for quick lookups. They're complementary, not competing."),
                    ("Measuring your impact", "Track your SnowWork usage in the \"My Progress\" tab. The most effective AEs average 5+ SnowWork interactions per day across account research, meeting prep, and pipeline management."),
                ],
                "pro_tip": "Make SnowWork your default starting point for any account-related task. If it can't do what you need, it'll tell you which tool can.",
            },
        ],
    },
]

TOTAL_LESSONS = sum(len(m["lessons"]) for m in MODULES)
TOTAL_DURATION = sum(m["duration_min"] for m in MODULES)


PROMPT_LIBRARY = [
    {"category": "Morning prep", "prompt": '"summarize my top 3 accounts"', "tool": "SnowWork", "description": "Portfolio overview with consumption, pipeline, and contract timelines for your top accounts"},
    {"category": "Morning prep", "prompt": '"brief me on [Account Name]"', "tool": "SnowWork", "description": "Full 10-section account brief: overview, consumption, pipeline, support tickets, and more"},
    {"category": "Morning prep", "prompt": '"/prospect_research [Company Name]"', "tool": "SnowWork", "description": "6-7 section prospect brief for non-customers: background, industry, value props, contacts"},
    {"category": "Account research", "prompt": '"/account_finder [Company Name]"', "tool": "SnowWork", "description": "Resolve company name to Salesforce account with full metadata: owner, segment, industry, type"},
    {"category": "Account research", "prompt": '"/consumption_insights [Account Name]"', "tool": "SnowWork", "description": "Run rate, overage/underage, and product mix for capacity customers"},
    {"category": "Account research", "prompt": '"/tech_stack [Account Name]"', "tool": "SnowWork", "description": "Tools and platforms in use at the account from Sumble signals"},
    {"category": "Account research", "prompt": '"/contact_intelligence [Account Name]"', "tool": "SnowWork", "description": "Key stakeholders, recent hires, hiring signals, and org changes"},
    {"category": "Account research", "prompt": '"/sec_filing_summary [Company Name]"', "tool": "SnowWork", "description": "10-K/10-Q highlights with earnings call insights and industry trends"},
    {"category": "Account research", "prompt": '"/partner_attachment_intelligence [Account Name]"', "tool": "SnowWork", "description": "Partner attach rates, deal registrations, DCP revenue, and co-sell opportunities"},
    {"category": "Meeting prep", "prompt": '"/account_summarization [Company Name]"', "tool": "SnowWork", "description": "Full account brief — the first step in every meeting prep workflow"},
    {"category": "Meeting prep", "prompt": '"/call_email_intelligence"', "tool": "SnowWork", "description": "Recent engagement history, unresolved items, and action items from past meetings"},
    {"category": "Meeting prep", "prompt": '"/knowledge_discovery_and_self_training [topic]"', "tool": "SnowWork", "description": "Search internal docs for product positioning or competitive angles"},
    {"category": "Pipeline", "prompt": '"/opportunity_monitoring"', "tool": "SnowWork", "description": "Flag deal hygiene issues: missing close dates, stale stages, pipeline gaps"},
    {"category": "Pipeline", "prompt": '"What moved in my pipeline this week?"', "tool": "SnowWork", "description": "Stage changes, new opps, deals closed, and push-outs — perfect for 1:1 prep"},
    {"category": "Pipeline", "prompt": '"/ps_attachment_intelligence [Account Name]"', "tool": "SnowWork", "description": "PS attach patterns, project delivery insights for similar deals"},
    {"category": "Customer comms", "prompt": '"Draft a follow-up email for my meeting with [company] covering [topics]"', "tool": "SnowWork", "description": "Data-grounded follow-up referencing account data and value propositions"},
    {"category": "Customer comms", "prompt": '"Create an executive brief for [company]\'s [role] showing [capabilities]"', "tool": "SnowWork", "description": "Tailored executive brief pulling from sales knowledge and account data"},
    {"category": "Competitive", "prompt": '"Give me the top 3 selling points against [competitor] for [use case]"', "tool": "SnowWork", "description": "Battlecard-level talking points from internal sources"},
    {"category": "Competitive", "prompt": '"Position Snowflake against [competitor] for [use case] at [account]"', "tool": "SnowWork", "description": "Account-specific competitive positioning combining battlecards and context"},
    {"category": "Account plans", "prompt": '"Generate an account plan for [Company Name]"', "tool": "SnowWork", "description": "8-tab HTML report with use cases, intelligence, and AI-powered recommendations"},
    {"category": "Account plans", "prompt": '"Reformat this as 3 bullet points for my RVP"', "tool": "SnowWork", "description": "Restructure any output for executive consumption"},
    {"category": "Custom skills", "prompt": '"Create a skill that pulls my pipeline changes from the last 7 days"', "tool": "SnowWork", "description": "Build a reusable custom skill from natural language description"},
]


TOOL_DATA = [
    {
        "name": "SnowWork (Falcon)",
        "icon": ":material/rocket_launch:",
        "best_for": "Multi-step business automation \u2014 account research, meeting prep, pipeline management, customer comms",
        "example": "Full account brief with pipeline, consumption, contacts, and strategic recommendations in one conversation",
        "audience": "Internal (Falcon) / Research Preview (external)",
        "depth": "Deep \u2014 multi-step, cross-system orchestration with 90+ skills",
        "tasks": ["Account research", "Meeting prep", "Pipeline management", "Customer comms", "Competitive intel", "Executive briefs", "Account plans", "Contact mapping", "Deal strategy"],
    },
    {
        "name": "Cortex Code (CoCo)",
        "icon": ":material/code:",
        "best_for": "AI coding agent for builders \u2014 SQL, pipelines, agents, and technical workflows",
        "example": "Build a data pipeline, debug a customer's semantic model, or create an agent in Snowsight",
        "audience": "Customer-facing (CLI approved for demos)",
        "depth": "Deep \u2014 full coding agent with IDE integration",
        "tasks": ["Pipeline building", "Customer demo", "Agent development", "SQL assistance", "Technical POC", "Data exploration"],
    },
    {
        "name": "Snowflake Intelligence",
        "icon": ":material/psychology:",
        "best_for": "Curated, governed data exploration for business users asking questions of their data",
        "example": "Help a data leader explore their own data with natural language \u2014 what happened, why, and what to do next",
        "audience": "Customer-facing (GA, 2,500+ customers)",
        "depth": "Medium \u2014 guided exploration with visualizations",
        "tasks": ["Customer data exploration", "Business user queries", "Governed insights", "Data visualization"],
    },
    {
        "name": "Raven",
        "icon": ":material/bolt:",
        "best_for": "Quick account lookups \u2014 ARR, pipeline, ownership, competitive intel, document search",
        "example": "Who owns this account? What's their ARR? Latest competitive intel on Databricks?",
        "audience": "Internal only",
        "depth": "Shallow \u2014 fast, single-answer lookups and document search",
        "tasks": ["Quick lookup", "ARR check", "Pipeline check", "Account ownership", "Competitive intel", "Document search"],
    },
]
